# Generated by Django 4.0.7 on 2022-09-09 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0003_assignment_attachment_assignment_body_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentclass',
            options={'verbose_name_plural': 'Student Classes'},
        ),
    ]
