# Generated by Django 4.0.7 on 2022-09-10 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0004_alter_studentclass_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclass',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_class', to='classApp.teacher'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='assignments/'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='body',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
